name: Translation Fix Request
description: Request a fix of translation for text or content in the launcher
title: "[TRANSLATION FIX] "
labels: ["translation fix"]
body:
  - type: input
    id: language
    attributes:
      label: Target Language
      description: What language do you want to translate to?
      placeholder: "e.g. Spanish (es-ES), Portuguese (pt-BR), etc."
    validations:
      required: true

  - type: textarea
    id: source_text
    attributes:
      label: Source Text
      description: The original text that needs to be translated.
      placeholder: "Paste the text here..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about where this text appears or how it's used.
      placeholder: "This text appears in..., It's used for..."

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any specific instructions or notes for the translator.